### ISSUE TITLE
Unable to sign up / login

### ISSUE THREAD

**Issue by freeslugs** [eiriklv/express-passport-app#7]
When trying to login or signup i get the error:

```
Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.renderComponentToStringWithAsyncState (/Users/freeslugs/Desktop/express-passport-app/node_modules/react-async/index.js:73:17)
    at module.exports (/Users/freeslugs/Desktop/express-passport-app/helpers/react/render-markup-to-string.js:19:16)
    at Stream._generator (/Users/freeslugs/Desktop/express-passport-app/node_modules/highland/lib/index.js:3671:15)
    at Stream._runGenerator (/Users/freeslugs/Desktop/express-passport-app/node_modules/highland/lib/index.js:870:10)
    at Stream.resume (/Users/freeslugs/Desktop/express-passport-app/node_modules/highland/lib/index.js:735:22)
    at Stream._checkBackPressure (/Users/freeslugs/Desktop/express-passport-app/node_modules/highland/lib/index.js:637:17)
```

I tried installing fibers, `npm install fibers` but that gives an error
and `npm install -g fibers` succeeds, but I still get the fibers error.

**Comment by mykolasmith** [comment]
Having the same issue

**Comment by eiriklv** [comment]
Which node version are you guys running?

**Comment by freeslugs** [comment]
i believe `v0.12.2`

**Comment by eiriklv** [comment]
I haven't upgraded/tested this on 0.12 I'm afraid :( 0.10.x should work though.
